DROP TABLE USERS CASCADE CONSTRAINTS;
DROP TABLE PLAYERS CASCADE CONSTRAINTS;
DROP TABLE REFEREES CASCADE CONSTRAINTS;
DROP TABLE HOUSE_LEAGUE CASCADE CONSTRAINTS;
DROP TABLE MATCH_STATS CASCADE CONSTRAINTS;
DROP TABLE MATCH_REFEREE CASCADE CONSTRAINTS;
DROP TABLE TEAMS CASCADE CONSTRAINTS;
